name: Build Android APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libssl-dev libffi-dev
          pip install --upgrade pip buildozer cython

      - name: Build APK with Buildozer
        run: |
          buildozer init
          sed -i 's/# title = My Application/title = MobileStream/' buildozer.spec
          sed -i 's/# package.name = myapp/package.name = mobilestream/' buildozer.spec
          sed -i 's/# package.domain = org.test/package.domain = org.imnotsneaker/' buildozer.spec
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy,flask,opencv,requests,gevent/g' buildozer.spec
          sed -i 's|# android.sdk_path =|android.sdk_path = /usr/local/lib/android/sdk|g' buildozer.spec
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
